### PR TITLE
Follow the newest flexible official implementation

### PR DESCRIPTION
**Pull request by ghost**
It is a big change. The “osenv” package use these code to generate the directory path:

``` javascript
  return (process.env.PATH ||
          process.env.Path ||
          process.env.path).split(isWindows ? ';' : ':')
```

> https://github.com/npm/osenv/blob/a83b10459f0f2214fe95f283fd12308cb31a0337/osenv.js#L66-L68

which is not good and not safe enough.

### CODE REVIEW

**Comment by dominictarr** [comment]
what makes this a breaking change?

Also, what is 'not safe' about the way osenv does it? if there is a security problem you need to explain that in detail.

btw you should not change the version number in a pull request, that is for the maintainer to do.

**Comment by ghost** [comment]
I've updated all my commits and restore the version number. All breaking changes are: (`module.exports` become a function to return a string)
1. Return the directory path as a string instead of an array of strings.
2. Guess the path from the widely used environment variables.
3. Dynamically generate the path and do not cache it.

It is not safe to use the directories from `PATH` for temporary files, if not be careful enough, it will make a lot of troubles, like truncating some important files. And on linux, usually these directories need administrative privileges to write, say, `/usr/bin` `/usr/local/bin` `/bin` `/sbin`.

**Comment by dominictarr** [comment]
this would be way better as a pull request to [osenv](https://github.com/npm/osenv) than here, I don't really understand the finer point of this like @npm does. That is why I just wrapped it... can you make a pull request there instead?

**Comment by ghost** [comment]
This function is so simple. Why would you want to add another dependency? And are you still trying to place temporary files in `PATH`?

**Comment by dominictarr** [comment]
this is just a wrapper module, if this is the right way to do it, it should be fixed in osenv.

**Comment by ghost** [comment]
Well, I don't like a wrapper like this. I'm just copy-pasting the official implementation here and it is sure this is recommended. If you feel good about my patch, please reopen this issue. Now I'm closing it.

**Pull request closed without merging**
